title:              Zhiyi Li Github Blog
email:              lizhiyidaniel@gmail.com
description:        Data Science Portofolios 
author:             Zhiyi Li
baseurl:            ""
url:                "https://lizhiyidaniel.github.io"

# Social Profiles
twitter_username:  
github_username:    lizhiyidaniel
facebook_username:  
instagram_username:  
linkedin_username: zhiyili99

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
